# @package _global_

defaults:
  - _self_
  - paths: default.yaml
  - hydra: default.yaml

task_name: "demo_scripted"

# checkpoint is necessary for demo
ckpt_path: ???

server_name: "0.0.0.0"
